# Generated by Django 4.2.10 on 2024-02-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_patient_alter_familymember_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='enforcedefaultbillno',
            field=models.BooleanField(blank=True, db_column='EnforceDefaultBillNo', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='infectiousdiseasesnotified',
            field=models.BooleanField(blank=True, db_column='InfectiousDiseasesNotified', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='policenotified',
            field=models.BooleanField(blank=True, db_column='PoliceNotified', null=True),
        ),
    ]
