# Generated by Django 4.2.10 on 2024-02-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_patient_enforcedefaultbillno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyinsurance',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='relationship',
            field=models.CharField(choices=[('principle', 'principle'), ('child', 'child'), ('spouse', 'spouse')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familymember',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
