# Generated by Django 4.2.10 on 2024-02-29 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_familyinsurance_status_familymember_membership_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.family'),
        ),
    ]
