# Generated by Django 4.2.10 on 2024-03-01 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_familymember_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinsurance',
            name='family',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.family'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.family'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.patient'),
        ),
        migrations.AlterField(
            model_name='patientaddress',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.patient'),
        ),
    ]
