# Generated by Django 4.2.10 on 2024-03-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_familyinsurance_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='scheme_no',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Scheme Number'),
        ),
    ]
