# Generated by Django 4.2.10 on 2024-03-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_familymember_scheme_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
