# Generated by Django 4.2.10 on 2024-03-11 16:29

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_familymember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='moa_document',
            field=models.FileField(blank=True, null=True, upload_to=manager.models.get_file_path, verbose_name='MOA Document'),
        ),
    ]
