# Generated by Django 4.2.10 on 2024-03-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_insuranceaccesstype_alter_familymember_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='access_type',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Basic', 'Basic')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
