# Generated by Django 4.2.10 on 2024-03-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_alter_familymember_access_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsuranceAccessType',
        ),
    ]
