# Generated by Django 4.2.10 on 2024-03-12 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_delete_insuranceaccesstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceAccessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('max_access_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maximum Usable Amount')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('max_access_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maximum Usable Amount')),
            ],
        ),
        migrations.AlterField(
            model_name='familymember',
            name='access_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.insuranceaccesstype'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relationship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.relationshiptype'),
        ),
    ]
