# Generated by Django 4.2.10 on 2024-03-12 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_insuranceaccesstype_relationshiptype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.family'),
        ),
    ]
