# Generated by Django 4.2.10 on 2024-03-18 11:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_alter_familymember_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=256, verbose_name='actions')),
                ('updated_on', models.DateField(blank=True, null=True, verbose_name='Created on')),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('insurance_number', models.CharField(blank=True, db_column='Insurance Number', max_length=100, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Credit On Account')),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_on', models.DateField(blank=True, null=True, verbose_name='Created on')),
            ],
        ),
        migrations.RemoveField(
            model_name='familyinsurance',
            name='family',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='family',
        ),
        migrations.AddField(
            model_name='familymember',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='updated_on',
            field=models.DateField(blank=True, null=True, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_on',
            field=models.DateField(blank=True, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientno',
            field=models.CharField(db_column='PatientNo', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='FamilyInsurance',
        ),
        migrations.AddField(
            model_name='familymember',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.scheme'),
        ),
    ]
