# Generated by Django 4.2.10 on 2024-03-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_log_scheme_remove_familyinsurance_family_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsuranceAccessType',
            new_name='AccessType',
        ),
    ]
