# Generated by Django 4.2.10 on 2024-03-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_rename_insuranceaccesstype_accesstype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_user',
            new_name='amount_used',
        ),
    ]
