# Generated by Django 4.2.10 on 2024-03-18 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_rename_amount_user_transaction_amount_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='patient',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.familymember'),
        ),
    ]
