# Generated by Django 4.2.10 on 2024-03-18 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_remove_transaction_patient_transaction_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.scheme'),
        ),
    ]
