# Generated by Django 4.2.10 on 2024-03-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_transaction_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_no',
            field=models.CharField(default=1, max_length=256, verbose_name='reference number'),
            preserve_default=False,
        ),
    ]
