# Generated by Django 4.2.10 on 2024-03-18 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_transaction_reference_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='log',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
    ]
