# Generated by Django 4.2.10 on 2024-03-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_remove_log_updated_on_log_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='reason'),
        ),
    ]
