# Generated by Django 4.2.10 on 2024-03-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_transaction_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymember',
            old_name='moa_document',
            new_name='mou_document',
        ),
    ]
