# Generated by Django 4.2.10 on 2024-03-29 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_rename_moa_document_familymember_mou_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('canExceedCredit', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='scheme',
            name='scheme_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.schemetype'),
        ),
    ]
