# Generated by Django 4.2.10 on 2024-03-29 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_schemetype_scheme_scheme_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeRemote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=256, verbose_name='file path')),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.scheme')),
            ],
        ),
    ]
