# Generated by Django 4.2.10 on 2024-03-29 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_schemeremote'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeremote',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
    ]
