# Generated by Django 4.2.10 on 2024-03-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_schemeremote_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='reason',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='schemetype',
            name='canExceedCredit',
            field=models.BooleanField(default=False, verbose_name='Can Exceed Credit'),
        ),
    ]
