# Generated by Django 4.2.10 on 2024-03-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_log_reason_alter_schemetype_canexceedcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(default=234, max_length=256, verbose_name='Code'),
            preserve_default=False,
        ),
    ]
