# Generated by Django 4.2.10 on 2024-04-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_transactionservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='service',
        ),
    ]
