# Generated by Django 4.2.10 on 2024-04-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_remove_transaction_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
