# Generated by Django 4.2.10 on 2024-04-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_alter_familymember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='depositor',
            field=models.CharField(blank=True, db_column='Depositor', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_mode',
            field=models.CharField(blank=True, db_column='Payment Mode', max_length=100, null=True),
        ),
    ]
