# Generated by Django 4.2.10 on 2024-04-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0034_transaction_depositor_transaction_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='patient_type',
            field=models.CharField(blank=True, db_column='Patient Type', max_length=100, null=True),
        ),
    ]
