# Generated by Django 4.2.10 on 2024-06-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0038_transactionservice_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionservice',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
